# Generated by Django 5.2.1 on 2025-05-13 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Applicable day of the week for this pricing config', max_length=3),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_additional_price',
            field=models.DecimalField(decimal_places=2, help_text='Per KM rate after base_km is exceeded', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_base_km',
            field=models.DecimalField(decimal_places=2, help_text='Distance covered in base price (in KMs)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for a distance up to base_km', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active config per day is used'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
            field=models.JSONField(help_text="Time multiplier based on ride duration (e.g. {'0-60':1, '61-120':1.25, '121-180':2.2})"),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_charges',
            field=models.DecimalField(decimal_places=2, help_text='Charge per 3 minutes after the first 3 minutes of waiting', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingconfiglog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='Action performed on the config', max_length=6),
        ),
        migrations.AlterField(
            model_name='pricingconfiglog',
            name='actor',
            field=models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
