# Generated by Django 5.2.1 on 2025-05-13 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricingconfig_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_additional_price',
            field=models.DecimalField(decimal_places=2, help_text='Rate per km after base distance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_base_km',
            field=models.DecimalField(decimal_places=2, help_text='Base kilometers covered in base price', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for distance up to distance_base_km', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
            field=models.JSONField(help_text="Time-based multiplier (e.g. {'0-60': 1, '61-120': 1.25, '121-180': 2.2})"),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_charges',
            field=models.DecimalField(decimal_places=2, help_text='Charge per 3 mins after initial 3 mins wait', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
