# Generated by Django 5.2.1 on 2025-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_pricingconfig_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Applicable day of the week for this pricing config', max_length=10),
        ),
    ]
